### ISSUE TITLE
Property setters have incorrect signature

### ISSUE THREAD

**Issue by torokati44** [cansik/nanobind-stubgen#2]
When generating stubs for a read-write attribute `flag`, they look like this:

```python3
    @property
    def flag(self) -> bool:
        ...
    @flag.setter
    def flag(self) -> bool:
        ...
```

The correct setter signature would be:

```python3
    @property
    def flag(self) -> bool:
        ...
    @flag.setter
    def flag(self, bool) -> None:
        ...
```

In addition, I think with newest `nanobind`, both methods are missig the name (`flag` here).

**Comment by cansik** [comment]
Thank you for reporting this issue, there was a copy and paste mistake I guess.
