### ISSUE TITLE
Incorrect Use of `Typing`

### ISSUE THREAD

**Issue by gandalfr-KY** [cansik/nanobind-stubgen#20]
Hello!

I attempted to create an API using `Sphinx` based on the `.pyi` files generated by `nanobind-stubgen`, but the build was interrupted due to an error. Upon inspecting the `.pyi` files produced by this project, it seems that the following import statement is incorrect. I referred to the official documentation and found that there appears to be no module named `Typing`. It might be a typo for `Type`.
```py
from typing import Any, Optional, overload, Typing, Sequence, Iterable, Union, Callable
                                            ^^^^^^
```

**Comment by cansik** [comment]
Thanks for the pr. Fyi stubgen capabilities are currently being implemented into nanobind directly: https://github.com/wjakob/nanobind/issues/420

**Comment by gandalfr-KY** [comment]
Thank you for the information!
