### ISSUE TITLE
Property getter and setter generated without method name

### ISSUE THREAD

**Issue by laggykiller** [cansik/nanobind-stubgen#5]
Discovered in my project: https://github.com/laggykiller/apngasm-python/tree/stubgen-fix

To build and reproduce
```bash
git clone --recursive https://github.com/laggykiller/apngasm-python.git
cd apngasm-python
git checkout stubgen-fix
python -m build .
```

https://github.com/laggykiller/apngasm-python/blob/stubgen-fix/src/apngasm_python.cpp#L239
```cpp
        .def_prop_rw("width", 
        [](apngasm::APNGFrame &t) APNGASM_PY_DECLSPEC { return t._width; },
        [](apngasm::APNGFrame &t, unsigned int v) APNGASM_PY_DECLSPEC { t.width(v); },
        R"pbdoc(
        The width of frame.
        )pbdoc")
```

The generated pyi
```python
    @property
    def (self) -> int:
        """
                The width of frame.
        """
        ...
    @width.setter
    def (self, arg: int, /) -> None:
        """
                The width of frame.
        """
        ...
```

The expected correct pyi generated should contain
```python
    @property
    def width(self) -> int:
        """
                The width of frame.
        """
        ...
    @width.setter
    def width(self, arg: int, /) -> None:
        """
                The width of frame.
        """
        ...
```

**Comment by cansik** [comment]
This should be fixed now and I am going to release a new version. Btw. the command `python -m build .` does not work since there is now `build` module available. Maybe there is an instruction missing? Anyway, it is much simpler to just install the pip package and call `nanobind-stubgen apngasm_python._apngasm_python`.

Btw. I also fixed the `ndarray` signatures.

**Comment by laggykiller** [comment]
Thank you for your hardwork. Can confirm the problem is fixed!

btw the command `python -m build .` requires `pip install build`

**Comment by laggykiller** [comment]
@cansik regarding ndarray signatures, would it be possible to automatically add `import numpy.typing` in the generated pyi file?

btw1 List is `List[]` instead of `list[]` for python <3.9, which would require either `from typing import List`, or replace all `List[]` to `list[]` and add `from __future__ import annotations`

btw2 For types that exist in same file (e.g. `_apngasm_python.APNGFrame`), I had to `from . import _apngasm_python` instead of `import _apngasm_python`. For example in `apngasm_python/_apngasm_python/__init__.pyi`:

```python
import _apngasm_python

class APNGAsm:
    """
    Class representing APNG file, storing APNGFrame(s) and other metadata.
    """

    def __init__(self, frames: list[_apngasm_python.APNGFrame]) -> None:
        """
        Construct APNGAsm object from an existing vector of apngasm frames.
        
        :param list[apngasm_python._apngasm_python.APNGFrame] frames: A list of APNGFrame objects.
        """
        ...
```

The `_apngasm_python.APNGFrame` would not be recognized, but changing `import _apngasm_python` to `from . import _apngasm_python` would allow recognition of `_apngasm_python.APNGFrame`

<img width="474" alt="image" src="https://github.com/cansik/nanobind-stubgen/assets/61652821/e470c018-6343-48bb-b083-566984530c22">

<img width="467" alt="image" src="https://github.com/cansik/nanobind-stubgen/assets/61652821/ae573fef-2542-4a40-ac93-c0d3cbd0c9ad">

In https://github.com/cansik/nanobind-stubgen/blob/main/nanobind_stubgen/NanobindStubsGenerator.py#L81 I propose to change from:

```python
# create init file
out = [f"from typing import Any, Optional, overload, Typing, Sequence",
       f"from enum import Enum",
       f"import {self.import_path}"]
```

To:
```python
# create init file
out = [f"from __future__ import annotations",
       f"from typing import Any, Optional, overload, Typing, Sequence",
       f"from enum import Enum",
       f"from . import {self.import_path}"]
```

...and append `import numpy.typing` to `out` if `numpy.typing` exist in signature, as well as replace `List[` with `list[` which is generated for python <3.9

Not sure if that would break other use cases though...

Alternatively, I can just patch on my end:
- Script: https://github.com/laggykiller/apngasm-python/blob/3d-array/scripts/patch_stub.py
- Result: https://github.com/laggykiller/apngasm-python/blob/3d-array/src-python/apngasm_python/_apngasm_python/__init__.pyi

However, it would be neat if this is handled automatically by the module

This is getting too long, please tell me if I need to open another issue

**Comment by cansik** [comment]
I guess a new issue would be great, otherwise I am also open for PR's anytime.

But regarding your questions:

'list' is parsed from nanobind docstring, but we can add a postprocessor of course

Imports are currently not handled well, it is more a guessing. I think it's necessary to add a proper import handling which detects modules and imports automatically.

**Comment by laggykiller** [comment]
@cansik opened a PR for that, plus fixing indentation in docstring
