### ISSUE TITLE
Infinite loop when generating stub for gt4py and aestream

### ISSUE THREAD

**Issue by laggykiller** [cansik/nanobind-stubgen#8]
While testing, I have discovered that generating stub for https://github.com/GridTools/gt4py and https://github.com/aestream/aestream result in infinite loop. I am not planning to use this project for generating stub for gt4py and aestream, but might be a good idea to investigate.

**Comment by cansik** [comment]
Don't use the python module as input, but just the nanobind generated part of it. This should solve the problem.

**Comment by laggykiller** [comment]
I see, thanks!

**Comment by cansik** [comment]
Maybe we can add something to prevent it from happening, I will have a look.
